# Generated by Django 6.0.3 on 2026-03-18 03:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pitch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=10)),
                ('entry_price', models.DecimalField(decimal_places=4, max_digits=10)),
                ('target_price', models.DecimalField(decimal_places=4, max_digits=10)),
                ('is_verified', models.BooleanField(default=False)),
                ('content_body', models.TextField()),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('CLOSED', 'Closed'), ('TARGET_HIT', 'Target Hit')], default='ACTIVE', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PitchAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_url', models.URLField(max_length=500)),
                ('file_type', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pitch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='core.pitch')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snaptrade_user_id', models.UUIDField(blank=True, null=True)),
                ('snaptrade_secret', models.CharField(blank=True, max_length=255, null=True)),
                ('total_alpha', models.DecimalField(decimal_places=4, default=0.0, max_digits=10)),
                ('win_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TradeEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=255, unique=True)),
                ('revenue_generated', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('executed_at', models.DateTimeField(auto_now_add=True)),
                ('pitch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_trades', to='core.pitch')),
                ('reader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades_executed', to='core.userprofile')),
            ],
        ),
        migrations.AddField(
            model_name='pitch',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pitches', to='core.userprofile'),
        ),
    ]
