# Generated by Django 6.0.3 on 2026-03-18 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_pitch_entry_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='pitch',
            name='current_alpha',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='pitch',
            name='spy_entry_price',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
    ]
