# Generated by Django 6.0.3 on 2026-03-21 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_hiddenpitch_portfoliosnapshot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pitchattachment',
            name='file_blob',
        ),
        migrations.AddField(
            model_name='pitchattachment',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='pitch_decks/'),
        ),
    ]
