# Generated by Django 6.0.3 on 2026-04-03 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_userprofile_auth_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pitch',
            name='current_alpha',
        ),
        migrations.RemoveField(
            model_name='pitch',
            name='spy_entry_price',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='total_alpha',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='win_rate',
        ),
    ]
